### ISSUE TITLE
Whats happen with python 3.6

### ISSUE THREAD

**Issue by Skorpyon** [aio-libs/aiohttp-benchmarks#1]
So why Python 3.6 slower that 3.5?!
Is it new general line in Python core developers strategy? py3 slower that py2, py3.6 slower that py3.5 :D
amazing

**Comment by samuelcolvin** [comment]
Main discussion going on at https://github.com/KeepSafe/aiohttp/issues/1614

Not sure why 3.6 is slower, as you can see with the new benchmarks using a remote server the different is is smaller.

However still a bit depressing as there was a rumour that 3.6 would improve performance of asyncio significantly.
