### ISSUE TITLE
Explaining benchmark results

### ISSUE THREAD

**Issue by xylik** [aio-libs/aiohttp-benchmarks#3]
Hi, am trying to understand benchmark results but am not sure what am actually looking at. Can you please explain what numbers in "Conc" and "2.3a" columns means in extracted row from bechmark results:

URL   python       DB  queries     Conc                 2.3a
/json      3.6          -        -               32                  5,349

**Comment by samuelcolvin** [comment]
Hi, 
* `Conc` refers to concurrency (I believe from memory this translates to the `-c` field in `wrk`
* `2.0             2.2            2.3a` refer to different version of aiohttp

These benchmarks are somewhat out of date, hence the old version of aiohttp.

**Comment by xylik** [comment]
So with 32 concurrent HTTP connections open to aiohttp server, max number of served json responses per second is around 5349 in particular benchmark.

**Comment by samuelcolvin** [comment]
yes, on version `2.3a` of aiohttp, but with aiohttp `2.0` you get 6,808.

Hope that makes sense.
